services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command:
      [
        "sh",
        "-c",
        "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      # optional: pass your API base URL into React (only used if your code reads it)
      - REACT_APP_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # keep node_modules inside the container so your host doesn’t clobber it
      - frontend_node_modules:/app/node_modules
    command: ["sh","-c","npm install && npm start"]
volumes:
  pgdata:
  frontend_node_modules:
