services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - COOKIE_SECURE=1
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command:
      [
        "sh",
        "-c",
        "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0

    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # keep node_modules inside the container so your host doesn’t clobber it
      - frontend_node_modules:/app/node_modules
    command: ["sh", "-c", "npm install && npm start"]
volumes:
  pgdata:
  frontend_node_modules:
