version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db #db: spins up PostgreSQL
      #backend: builds your FastAPI app image, links to db, and mounts your source so edits reload in dev
    ports:
      - "8000:8000"
    environment:
      - .env
    volumes:
      - ./backend:/app # so code changes reflect immediately
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
