"""add name to grocery_list

Revision ID: 111091cec1ca
Revises: 49bb37e65fd3
Create Date: 2025-07-29 00:13:52.298781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111091cec1ca'
down_revision: Union[str, Sequence[str], None] = '49bb37e65fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_list', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery_list', 'name')
    # ### end Alembic commands ###
