"""add list_item, set owner_id not null, add cascades

Revision ID: 142f68bc01b9
Revises: 111091cec1ca
Create Date: 2025-08-13 21:52:21.987911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142f68bc01b9'
down_revision: Union[str, Sequence[str], None] = '111091cec1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['grocery_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('grocery_list', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('grocery_list_owner_id_fkey'), 'grocery_list', type_='foreignkey')
    op.create_foreign_key(None, 'grocery_list', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grocery_list', type_='foreignkey')
    op.create_foreign_key(op.f('grocery_list_owner_id_fkey'), 'grocery_list', 'user', ['owner_id'], ['id'])
    op.alter_column('grocery_list', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('list_item')
    # ### end Alembic commands ###
