"""google sso fields

Revision ID: a028b9060362
Revises: 9483bfad800c
Create Date: 2025-08-21 23:21:22.665992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a028b9060362'
down_revision: Union[str, Sequence[str], None] = '9483bfad800c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_sub', sa.String(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('picture', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'picture')
    op.drop_column('user', 'name')
    op.drop_column('user', 'google_sub')
    # ### end Alembic commands ###
