name: backend-tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # Start a Postgres service the job can use at localhost:5432
    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: smartgrocery_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t sgl-backend ./backend

      # Run pytest inside the backend image, mounting your backend code,
      # and pointing DATABASE_URL_TEST to the job's Postgres service.
      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e PYTHONPATH=/app \
            -e DATABASE_URL_TEST="postgresql+psycopg2://postgres:postgres@localhost:5432/smartgrocery_test" \
            -v "$PWD/backend":/app \
            sgl-backend pytest -q
