name: Reminders

on:
  schedule:
    # Daily at 14:00 UTC — adjust as needed
    - cron: '0 14 * * *'
  # Allow manual run from the Actions tab
  workflow_dispatch: {}

concurrency:
  group: reminders
  cancel-in-progress: false

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call backend reminder task
        env:
          API_URL: https://api.smartgrocery.online
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$CRON_SECRET" ]; then
            echo "CRON_SECRET is not set in repo secrets" >&2
            exit 1
          fi
          # POST to the secured task endpoint with the secret header
          curl -fsS -X POST "$API_URL/tasks/run-reminders" \
            -H "x-api-key: $CRON_SECRET" \
            -H "User-Agent: gh-actions-reminders/1.0"

